# Generated by Django 6.0.2 on 2026-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('achievements', models.CharField()),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
